#!/usr/bin/env python3
"""Generate thesis/abbreviations.tex from the bold first uses in the thesis body.

The writing convention is that a term is set in \\textbf at its first use, with its
abbreviation in parentheses:

    \\textbf{left anterior descending artery (LAD)}

This script collects exactly those, in reading order, and writes the front-matter list.
Run it after editing any section; never hand-edit the generated file.

    python scripts/make_abbreviations.py            # write thesis/abbreviations.tex
    python scripts/make_abbreviations.py --check    # verify only, non-zero exit on a problem

--check enforces the two rules the convention depends on: an abbreviation is defined
exactly once, and it is never used before the sentence that defines it.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "thesis" / "abbreviations.tex"

# Directories holding thesis body text, in the order a reader meets them.
BODY_DIRS = [
    "thesis/introduction",
    "thesis/clinical_background",
    "thesis/state_of_the_art",
    "thesis/dataset",
]

BOLD_DEF = re.compile(r"\\textbf\{([^{}]*?)\s*\(([A-Z][A-Z0-9-]*[A-Z0-9])\)\}")
COMMENT = re.compile(r"(?<!\\)%.*$")


def body_files():
    """Every body .tex file, in reading order."""
    files = []
    for d in BODY_DIRS:
        files.extend(sorted((ROOT / d).glob("*.tex")))
    return files


def read_lines(path):
    """Lines with LaTeX comments stripped, so a comment can never define or use a term."""
    return [COMMENT.sub("", line) for line in path.read_text().splitlines()]


def collect():
    """Return (definitions, corpus). definitions maps abbr -> (full, position, path, lineno)."""
    definitions = {}
    duplicates = []
    corpus = []
    for file_index, path in enumerate(body_files()):
        for lineno, line in enumerate(read_lines(path), start=1):
            corpus.append(((file_index, lineno), path, line))
            for full, abbr in BOLD_DEF.findall(line):
                if abbr in definitions:
                    duplicates.append((abbr, definitions[abbr][2], definitions[abbr][3], path, lineno))
                else:
                    definitions[abbr] = (full, (file_index, lineno), path, lineno)
    return definitions, corpus, duplicates


def first_use(abbr, corpus):
    """Position of the first bare occurrence of the abbreviation anywhere in the body."""
    pattern = re.compile(r"(?<![A-Za-z0-9-])" + re.escape(abbr) + r"(?![A-Za-z0-9-])")
    for position, path, line in corpus:
        if pattern.search(line):
            return position, path
    return None, None


def rel(path):
    return path.relative_to(ROOT)


def check(definitions, corpus, duplicates):
    problems = []
    for abbr, first_path, first_line, again_path, again_line in duplicates:
        problems.append(
            f"{abbr}: defined twice -- {rel(first_path)}:{first_line} and {rel(again_path)}:{again_line}"
        )
    for abbr, (_full, defined_at, def_path, def_line) in sorted(definitions.items()):
        used_at, use_path = first_use(abbr, corpus)
        if used_at is not None and used_at < defined_at:
            problems.append(
                f"{abbr}: used at {rel(use_path)}:{used_at[1]} before its definition at "
                f"{rel(def_path)}:{def_line}"
            )
    return problems


def render(definitions):
    scanned = ", ".join(BODY_DIRS)
    lines = [
        "% GENERATED by scripts/make_abbreviations.py -- do not edit by hand.",
        f"% Collected from \\textbf{{term (ABBR)}} first uses in: {scanned}",
        "% An abbreviation missing here is one its section has not yet bolded at first use.",
        "",
        "\\chapter*{Abbreviations}",
        "\\addcontentsline{toc}{chapter}{Abbreviations}",
        "",
        "\\begin{description}",
    ]
    for abbr in sorted(definitions, key=lambda a: (a.upper(), a)):
        full = definitions[abbr][0]
        full = full[0].upper() + full[1:] if full else full
        lines.append(f"  \\item[{abbr}] {full}")
    lines += ["\\end{description}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = parser.parse_args()

    definitions, corpus, duplicates = collect()
    problems = check(definitions, corpus, duplicates)
    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1

    if args.check:
        print(f"{len(definitions)} abbreviations, each defined once and before first use")
        return 0

    OUT.write_text(render(definitions))
    print(f"wrote {rel(OUT)} with {len(definitions)} abbreviations")
    return 0


if __name__ == "__main__":
    sys.exit(main())
